<?php

namespace Sogedial\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Sogedial\SiteBundle\Entity\ClientMeti;

/**
 * ClientMetiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientMetiRepository extends EntityRepository
{
    /**
     * @param $codeClient
     * @return array
     */
    public function getClientObjectsFromCodeClient($codeClient)
    {

        $qb = $this->createQueryBuilder('cl');

        $qb->add('select', 'cl')
            ->add('from', 'SogedialSiteBundle:Client cl')
            ->where('cl.code LIKE :codeClient');

        $qb->setParameter('codeClient', '%'.$codeClient.'%');

        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
