<?php

namespace Sogedial\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepriseRepository extends EntityRepository
{
    /**
     * @param $codeRegion
     * @return array
     */
    public function getListSocieteByCodeRegion($codeRegion)
    {
        $qb = $this->_em->createQueryBuilder();

        $result = $qb
            ->select('e.raisonSociale, e.nomEnvironnement, e.code as codeEntreprise')
            ->from('SogedialSiteBundle:Entreprise', 'e')
            ->leftJoin('e.region', 'r')
            ->where('e.region = :codeRegion')
            ->setParameter('codeRegion', $codeRegion)
            ->getQuery()
            ->getArrayResult()
        ;

        return $result;
    }
}