<?php

namespace Sogedial\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderOrderStatusRepository extends EntityRepository
{

    /**
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getPendingOrdersCount()
    {
        $qb = $this->createQueryBuilder('o');
        $qb->select('COUNT(o.order)')
           ->where('o.orderStatus = :pendingStatusId');

        $qb->setParameter('pendingStatusId', 2);
        return $qb->getQuery()->getSingleScalarResult();
    }

}
