<?php

namespace Sogedial\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FamilySelectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilySelectionRepository extends EntityRepository {

  public function deleteFamilySelectionsOfUser($userId) {
    return $this->getEntityManager()
                    ->createQuery('
        DELETE
        FROM SogedialUserBundle:FamilySelection u
        WHERE u.user = :uid'
                    )
        ->setParameter('uid', $userId)
        ->getResult();
  }
  
  public function deleteFamilyFromUser($userId, $familyId){
    $query = 'DELETE
              FROM SogedialUserBundle:FamilySelection u
              WHERE u.user = :user_id
              AND (u.entity = :family_id OR
                   u.entity IN (SELECT f21.id 
                               FROM SogedialSiteBundle:Famille f21
                               JOIN f21.parent f11
                               WHERE f11.id = :family_id) OR
                   u.entity IN (SELECT f32.id
                                FROM SogedialSiteBundle:Famille f32
                                JOIN f32.parent f22
                                JOIN f22.parent f12
                                WHERE f12.id = :family_id) OR
                   u.entity IN (SELECT f43.id
                                FROM SogedialSiteBundle:Famille f43
                                JOIN f43.parent f33
                                JOIN f33.parent f23
                                JOIN f23.parent f13
                                WHERE f13.id = :family_id) OR
                   u.entity IN (SELECT f54.id
                                FROM SogedialSiteBundle:Famille f54
                                JOIN f54.parent f44
                                JOIN f44.parent f34
                                JOIN f34.parent f24
                                JOIN f24.parent f14
                                WHERE f14.id = :family_id))';
    $queryb = $this->getEntityManager()->createQuery($query);
    
    $queryb->setParameter('user_id', $userId);
    $queryb->setParameter('family_id', $familyId);

    return $queryb->getResult();
  }
  
  public function findAssortimentUser($family, $user_id) {
    $query = 'SELECT count(u)
              FROM SogedialUserBundle:FamilySelection u
              JOIN u.entity f';
    
    $query .= ' WHERE IDENTITY(u.user) = :user_id 
      ';
    
    if($family->getType() == 1){
      $query .= ' AND (f.id IN (SELECT f2.id
                                FROM SogedialSiteBundle:Famille f2
                                JOIN f2.parent f1
                                WHERE f1.id = :family_id) OR 
                       f.id IN (SELECT f3.id
                                FROM SogedialSiteBundle:Famille f3
                                JOIN f3.parent f21
                                JOIN f21.parent f11
                                WHERE  f11.id = :family_id) OR
                       f.id IN (SELECT f4.id 
                                FROM SogedialSiteBundle:Famille f4
                                JOIN f4.parent f32
                                JOIN f32.parent f22
                                JOIN f22.parent f12
                                WHERE f12.id = :family_id) OR 
                       f.id IN (SELECT f5.id 
                                FROM SogedialSiteBundle:Famille f5
                                JOIN f5.parent f43
                                JOIN f43.parent f33
                                JOIN f33.parent f23
                                JOIN f23.parent f13
                                WHERE f13.id = :family_id) )';
    }
    elseif($family->getType() == 2){
      $query .= ' AND (f.id IN (SELECT f3.id
                                FROM SogedialSiteBundle:Famille f3
                                JOIN f3.parent f21
                                JOIN f21.parent f11
                                WHERE  f11.id = :family_id) OR
                       f.id IN (SELECT f4.id 
                                FROM SogedialSiteBundle:Famille f4
                                JOIN f4.parent f32
                                JOIN f32.parent f22
                                JOIN f22.parent f12
                                WHERE f12.id = :family_id) OR 
                       f.id IN (SELECT f5.id 
                                FROM SogedialSiteBundle:Famille f5
                                JOIN f5.parent f43
                                JOIN f43.parent f33
                                JOIN f33.parent f23
                                JOIN f23.parent f13
                                WHERE f13.id = :family_id) )';
    }
    elseif($family->getType() == 3){
      $query .= ' AND (f.id IN (SELECT f4.id 
                                FROM SogedialSiteBundle:Famille f4
                                JOIN f4.parent f32
                                JOIN f32.parent f22
                                JOIN f22.parent f12
                                WHERE f12.id = :family_id) OR 
                       f.id IN (SELECT f5.id 
                                FROM SogedialSiteBundle:Famille f5
                                JOIN f5.parent f43
                                JOIN f43.parent f33
                                JOIN f33.parent f23
                                JOIN f23.parent f13
                                WHERE f13.id = :family_id) )';
    }
    elseif($family->getType() == 4){
      $query .= ' AND (f.id IN (SELECT f5.id 
                                FROM SogedialSiteBundle:Famille f5
                                JOIN f5.parent f43
                                JOIN f43.parent f33
                                JOIN f33.parent f23
                                JOIN f23.parent f13
                                WHERE f13.id = :family_id) )';
    }
    else{
      return array(1 => 0);
    }
    
    $queryb = $this->getEntityManager()->createQuery($query);
    $queryb->setParameter('user_id', $user_id);
    $queryb->setParameter('family_id', $family->getId());

    return $queryb->getOneOrNullResult();
  }

    public function findFamilySelectionsByUser($user) {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('f.id as familleId,fs.show_promotion,fs.show_exclusivity,fs.is_new,fs.coefficient')
        ->from('SogedialUserBundle:FamilySelection','fs')
        ->leftjoin('fs.entity','f')
            ->where('fs.user = :user')
            ->setParameter('user',$user);

        return $qb->getQuery()->getArrayResult();
    }

}
