<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150113230057 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf(
            $this->connection->getDatabasePlatform()->getName() != 'mysql',
            'Migration can only be executed safely on \'mysql\'.'
        );

        $this->addSql(
            'UPDATE `famille` SET `libelle_famille_en`="LOCAL FAMILY" WHERE id_famille = 1;
UPDATE `famille` SET `libelle_famille_en`="GROSSERY" WHERE id_famille = 2;
UPDATE `famille` SET `libelle_famille_en`="FRESH PRODUCTS" WHERE id_famille = 3;
UPDATE `famille` SET `libelle_famille_en`="GENERAL STORE GOODS" WHERE id_famille = 4;
UPDATE `famille` SET `libelle_famille_en`="TEXTILE" WHERE id_famille = 5;
UPDATE `famille` SET `libelle_famille_en`="MARKET AREA" WHERE id_famille = 6;
UPDATE `famille` SET `libelle_famille_en`="GAS STATION" WHERE id_famille = 7;
UPDATE `famille` SET `libelle_famille_en`="GOLD SHOP" WHERE id_famille = 8;
UPDATE `famille` SET `libelle_famille_en`="HEAVY GENERAL STORE PRODUCTS" WHERE id_famille = 9;
UPDATE `famille` SET `libelle_famille_en`="LOCAL FAMILY" WHERE id_famille = 11;
UPDATE `famille` SET `libelle_famille_en`="LIQUIDS" WHERE id_famille = 12;
UPDATE `famille` SET `libelle_famille_en`="DRUG PERFUME HYGIENE" WHERE id_famille = 13;
UPDATE `famille` SET `libelle_famille_en`="PHARMACEUTICAL" WHERE id_famille = 14;
UPDATE `famille` SET `libelle_famille_en`="DRY GROCERY" WHERE id_famille = 15;
UPDATE `famille` SET `libelle_famille_en`="OPTICAL" WHERE id_famille = 16;
UPDATE `famille` SET `libelle_famille_en`="PACKAGING" WHERE id_famille = 17;
UPDATE `famille` SET `libelle_famille_en`="EXTRA FRESH PRODUCTS" WHERE id_famille = 18;
UPDATE `famille` SET `libelle_famille_en`="DAIRY SELF SERVICE" WHERE id_famille = 19;
UPDATE `famille` SET `libelle_famille_en`="DELICATESSEN SELF SERVICE" WHERE id_famille = 20;
UPDATE `famille` SET `libelle_famille_en`="SMOKING HOUSE SEAFOOD" WHERE id_famille = 21;
UPDATE `famille` SET `libelle_famille_en`="POULTRY SELF SERVICE" WHERE id_famille = 22;
UPDATE `famille` SET `libelle_famille_en`="PRODUCTS" WHERE id_famille = 23;
UPDATE `famille` SET `libelle_famille_en`="ICE CREAM" WHERE id_famille = 24;
UPDATE `famille` SET `libelle_famille_en`="FLOWERS PLANTS" WHERE id_famille = 25;
UPDATE `famille` SET `libelle_famille_en`="DIY PRODUCTS" WHERE id_famille = 26;
UPDATE `famille` SET `libelle_famille_en`="HOUSING CLEANING PRODUCTS" WHERE id_famille = 27;
UPDATE `famille` SET `libelle_famille_en`="STATIONERY PRODUCTS" WHERE id_famille = 28;
UPDATE `famille` SET `libelle_famille_en`="BOOKSTORE" WHERE id_famille = 29;
UPDATE `famille` SET `libelle_famille_en`="BLANK TAPE" WHERE id_famille = 30;
UPDATE `famille` SET `libelle_famille_en`="GARDEN AND CAMPING PRODUCTS" WHERE id_famille = 31;
UPDATE `famille` SET `libelle_famille_en`="HOME IMPROVEMENT GOODSPRODUCTS" WHERE id_famille = 32;
UPDATE `famille` SET `libelle_famille_en`="CAR PRODUCTS" WHERE id_famille = 33;
UPDATE `famille` SET `libelle_famille_en`="TOYS" WHERE id_famille = 34;
UPDATE `famille` SET `libelle_famille_en`="LUGGAGE" WHERE id_famille = 35;
UPDATE `famille` SET `libelle_famille_en`="WHITE" WHERE id_famille = 36;
UPDATE `famille` SET `libelle_famille_en`="BABY CLOTHE" WHERE id_famille = 37;
UPDATE `famille` SET `libelle_famille_en`="KIDS" WHERE id_famille = 38;
UPDATE `famille` SET `libelle_famille_en`="WOMAN" WHERE id_famille = 39;
UPDATE `famille` SET `libelle_famille_en`="MAN" WHERE id_famille = 40;
UPDATE `famille` SET `libelle_famille_en`="CHILDCARE" WHERE id_famille = 41;
UPDATE `famille` SET `libelle_famille_en`="UNDERWEAR" WHERE id_famille = 42;
UPDATE `famille` SET `libelle_famille_en`="PANTYHOSE TIGHTS FOR LADIES" WHERE id_famille = 43;
UPDATE `famille` SET `libelle_famille_en`="STOCKINGS FOR LADIES" WHERE id_famille = 44;
UPDATE `famille` SET `libelle_famille_en`="DELICATESSEN CATERING" WHERE id_famille = 45;
UPDATE `famille` SET `libelle_famille_en`="DAIRY SELF SERVICE" WHERE id_famille = 46;
UPDATE `famille` SET `libelle_famille_en`="BUTCHERY SELF SERVICE" WHERE id_famille = 47;
UPDATE `famille` SET `libelle_famille_en`="FISH STAND" WHERE id_famille = 48;
UPDATE `famille` SET `libelle_famille_en`="BAKERY" WHERE id_famille = 49;
UPDATE `famille` SET `libelle_famille_en`="PASTRY" WHERE id_famille = 50;
UPDATE `famille` SET `libelle_famille_en`="FRUITS AND VEGETABLES" WHERE id_famille = 51;
UPDATE `famille` SET `libelle_famille_en`="TRADITIONAL BUTCHERY" WHERE id_famille = 52;
UPDATE `famille` SET `libelle_famille_en`="PIZZA - COOKED MEAT" WHERE id_famille = 53;
UPDATE `famille` SET `libelle_famille_en`="TAKE AWAY MEALS" WHERE id_famille = 54;
UPDATE `famille` SET `libelle_famille_en`="SHOES" WHERE id_famille = 55;
UPDATE `famille` SET `libelle_famille_en`="TEXTIL SHOP" WHERE id_famille = 56;
UPDATE `famille` SET `libelle_famille_en`="SPORT" WHERE id_famille = 57;
UPDATE `famille` SET `libelle_famille_en`="BIKE" WHERE id_famille = 58;
UPDATE `famille` SET `libelle_famille_en`="SMALL ELECTRICAL HOUSEHOLD" WHERE id_famille = 59;
UPDATE `famille` SET `libelle_famille_en`="HEAVY ELECTRICAL HOUSEHOLD" WHERE id_famille = 60;
UPDATE `famille` SET `libelle_famille_en`="PHOTO" WHERE id_famille = 61;
UPDATE `famille` SET `libelle_famille_en`="PHONE" WHERE id_famille = 62;
UPDATE `famille` SET `libelle_famille_en`="MUSIC" WHERE id_famille = 63;
UPDATE `famille` SET `libelle_famille_en`="GIFT SHOP" WHERE id_famille = 64;
UPDATE `famille` SET `libelle_famille_en`="VIDEO" WHERE id_famille = 65;
UPDATE `famille` SET `libelle_famille_en`="TV VCR" WHERE id_famille = 66;
UPDATE `famille` SET `libelle_famille_en`="HI FI / AUDIO" WHERE id_famille = 67;
UPDATE `famille` SET `libelle_famille_en`="TRAVELLING GOODS" WHERE id_famille = 68;
UPDATE `famille` SET `libelle_famille_en`="GOLD SHOP" WHERE id_famille = 69;
UPDATE `famille` SET `libelle_famille_en`="MINI LAB" WHERE id_famille = 70;
UPDATE `famille` SET `libelle_famille_en`="CELLPHONE" WHERE id_famille = 71;
UPDATE `famille` SET `libelle_famille_en`="MICRO COMPUTING" WHERE id_famille = 72;
UPDATE `famille` SET `libelle_famille_en`="TRANSPORT FUEL" WHERE id_famille = 73;
UPDATE `famille` SET `libelle_famille_en`="FUEL" WHERE id_famille = 74;
UPDATE `famille` SET `libelle_famille_en`="VIDEOGAME" WHERE id_famille = 75;
UPDATE `famille` SET `libelle_famille_en`="DO NOT USE" WHERE id_famille = 76;
UPDATE `famille` SET `libelle_famille_en`="CUSTOMER SERVICE" WHERE id_famille = 77;
UPDATE `famille` SET `libelle_famille_en`="LOCAL FAMILY" WHERE id_famille = 78;
UPDATE `famille` SET `libelle_famille_en`="YOGHURT" WHERE id_famille = 79;
UPDATE `famille` SET `libelle_famille_en`="DESSERTS" WHERE id_famille = 80;
UPDATE `famille` SET `libelle_famille_en`="SUISSES" WHERE id_famille = 81;
UPDATE `famille` SET `libelle_famille_en`="FRESH CHEESE" WHERE id_famille = 82;
UPDATE `famille` SET `libelle_famille_en`="FRESH CREAM/CREAM PRODUCT" WHERE id_famille = 83;
UPDATE `famille` SET `libelle_famille_en`="FRUITS JUICES AND NECTARS" WHERE id_famille = 84;
UPDATE `famille` SET `libelle_famille_en`="FRESH BREAKFAST" WHERE id_famille = 85;
UPDATE `famille` SET `libelle_famille_en`="FRESH MILK" WHERE id_famille = 86;
UPDATE `famille` SET `libelle_famille_en`="BUTTER AND DAIRY SPECIALITIES" WHERE id_famille = 87;
UPDATE `famille` SET `libelle_famille_en`="VEGETABLE MARGARINE" WHERE id_famille = 88;
UPDATE `famille` SET `libelle_famille_en`="SPREADS" WHERE id_famille = 89;
UPDATE `famille` SET `libelle_famille_en`="MILK SELF SERVICE" WHERE id_famille = 90;
UPDATE `famille` SET `libelle_famille_en`="MILK PRODUCTS UHT" WHERE id_famille = 91;
UPDATE `famille` SET `libelle_famille_en`="EGGS" WHERE id_famille = 92;
UPDATE `famille` SET `libelle_famille_en`="CHEESE SELF SERVICE" WHERE id_famille = 93;
UPDATE `famille` SET `libelle_famille_en`="APERITIF CHEESE CUBE" WHERE id_famille = 94;
UPDATE `famille` SET `libelle_famille_en`="EGGS PRODUCTS CATERING PRODUCTS" WHERE id_famille = 95;
UPDATE `famille` SET `libelle_famille_en`="PACKAGED DELICATESSEN" WHERE id_famille = 96;
UPDATE `famille` SET `libelle_famille_en`="HAM DRY SAUSAGES SELF SERVICE" WHERE id_famille = 97;
UPDATE `famille` SET `libelle_famille_en`="CATERING SELF SERVICE" WHERE id_famille = 98;
UPDATE `famille` SET `libelle_famille_en`="HALAL/KOSHER" WHERE id_famille = 99;
UPDATE `famille` SET `libelle_famille_en`="ROASTED, DRY AND SALT FISH" WHERE id_famille = 100;
UPDATE `famille` SET `libelle_famille_en`="MARINADE" WHERE id_famille = 101;
UPDATE `famille` SET `libelle_famille_en`="COUCH PRODUCTS" WHERE id_famille = 102;
UPDATE `famille` SET `libelle_famille_en`="SEAFOOD CATERING" WHERE id_famille = 103;
UPDATE `famille` SET `libelle_famille_en`="CHICKEN SELF SERVICE" WHERE id_famille = 104;
UPDATE `famille` SET `libelle_famille_en`="TURKEY SELF SERVICE" WHERE id_famille = 105;
UPDATE `famille` SET `libelle_famille_en`="DUCK AND GOOSE SELF SERVICE" WHERE id_famille = 106;
UPDATE `famille` SET `libelle_famille_en`="GUINEA FOWL" WHERE id_famille = 107;
UPDATE `famille` SET `libelle_famille_en`="QUAIL, PIGEON AND GAME SELF SERVICE" WHERE id_famille = 108;
UPDATE `famille` SET `libelle_famille_en`="RABBIT SELF SERVICE" WHERE id_famille = 109;
UPDATE `famille` SET `libelle_famille_en`="RAW POULTRY OFFAL SELF SERVICE" WHERE id_famille = 110;
UPDATE `famille` SET `libelle_famille_en`="COOKED AND RAW ELABORATED PRODUCTS" WHERE id_famille = 111;
UPDATE `famille` SET `libelle_famille_en`="PETFOOD SELF SERVICE" WHERE id_famille = 112;
UPDATE `famille` SET `libelle_famille_en`="BEEF SELF SERVICE" WHERE id_famille = 114;
UPDATE `famille` SET `libelle_famille_en`="CALF SELF SERVICE" WHERE id_famille = 115;
UPDATE `famille` SET `libelle_famille_en`="LAMB SELF SERVICE" WHERE id_famille = 116;
UPDATE `famille` SET `libelle_famille_en`="SHEEP SELF SERVICE" WHERE id_famille = 117;
UPDATE `famille` SET `libelle_famille_en`="PORK SELF SERVICE" WHERE id_famille = 118;
UPDATE `famille` SET `libelle_famille_en`="HORSE SELF SERVICE" WHERE id_famille = 119;
UPDATE `famille` SET `libelle_famille_en`="GROUND BEEF SELF SERVICE" WHERE id_famille = 120;
UPDATE `famille` SET `libelle_famille_en`="ELABORATED PRODUCTS SELF SERVICE" WHERE id_famille = 121;
UPDATE `famille` SET `libelle_famille_en`="RAW OFFAL SELF SERVICE" WHERE id_famille = 122;
UPDATE `famille` SET `libelle_famille_en`="OTHER MEET SELF SERVICE" WHERE id_famille = 123;
UPDATE `famille` SET `libelle_famille_en`="MEET PETFOOD SELF SERVICE" WHERE id_famille = 124;
UPDATE `famille` SET `libelle_famille_en`="SLICED POULTRY BUTCHERY SELF SERVICE" WHERE id_famille = 125;
UPDATE `famille` SET `libelle_famille_en`="BULL SELF SERVICE" WHERE id_famille = 126;
UPDATE `famille` SET `libelle_famille_en`="FROZEN BROTHS AND STARTERS" WHERE id_famille = 132;
UPDATE `famille` SET `libelle_famille_en`="FISH, SEAFOOD, SNAIL" WHERE id_famille = 133;
UPDATE `famille` SET `libelle_famille_en`="FROZEN MEET AND OFFAL" WHERE id_famille = 134;
UPDATE `famille` SET `libelle_famille_en`="FROZEN POTATOES GARNISH" WHERE id_famille = 135;
UPDATE `famille` SET `libelle_famille_en`="FROZEN VEGETABLE" WHERE id_famille = 136;
UPDATE `famille` SET `libelle_famille_en`="FROZEN COOKED MEAL" WHERE id_famille = 137;
UPDATE `famille` SET `libelle_famille_en`="FROZEN PASTRY AND PASTA" WHERE id_famille = 138;
UPDATE `famille` SET `libelle_famille_en`="FROZEN FRUIT AND FRUIT JUICE" WHERE id_famille = 139;
UPDATE `famille` SET `libelle_famille_en`="COOKING AID" WHERE id_famille = 140;
UPDATE `famille` SET `libelle_famille_en`="BULK ICE CREAM" WHERE id_famille = 142;
UPDATE `famille` SET `libelle_famille_en`="ICE CREAM SELF SERVICE" WHERE id_famille = 143;
UPDATE `famille` SET `libelle_famille_en`="INDIVIDUAL ICE CREAM" WHERE id_famille = 144;
UPDATE `famille` SET `libelle_famille_en`="SLICED DELICATESSEN" WHERE id_famille = 145;
UPDATE `famille` SET `libelle_famille_en`="SLICED CATERING" WHERE id_famille = 146;
UPDATE `famille` SET `libelle_famille_en`="PIZZA QUICHE STALL" WHERE id_famille = 147;
UPDATE `famille` SET `libelle_famille_en`="ROTISSERIE STALL" WHERE id_famille = 148;
UPDATE `famille` SET `libelle_famille_en`="SANDWICH STALL" WHERE id_famille = 149;
UPDATE `famille` SET `libelle_famille_en`="FRESH PACKAGED DELICATESSEN" WHERE id_famille = 150;
UPDATE `famille` SET `libelle_famille_en`="FRESH PACKAGED CATERING" WHERE id_famille = 151;
UPDATE `famille` SET `libelle_famille_en`="SLICED CHEESE" WHERE id_famille = 153;
UPDATE `famille` SET `libelle_famille_en`="OTHER SLICED DAIRY PRODUCTS" WHERE id_famille = 154;
UPDATE `famille` SET `libelle_famille_en`="FRESH PACKAGED CHEESE" WHERE id_famille = 155;
UPDATE `famille` SET `libelle_famille_en`="FRESH PACKAGED BUTCHERY" WHERE id_famille = 163;
UPDATE `famille` SET `libelle_famille_en`="BEEF" WHERE id_famille = 167;
UPDATE `famille` SET `libelle_famille_en`="VEAL" WHERE id_famille = 168;
UPDATE `famille` SET `libelle_famille_en`="LAMB" WHERE id_famille = 169;
UPDATE `famille` SET `libelle_famille_en`="SHEEP" WHERE id_famille = 170;
UPDATE `famille` SET `libelle_famille_en`="PORK" WHERE id_famille = 171;
UPDATE `famille` SET `libelle_famille_en`="POULTRY" WHERE id_famille = 172;
UPDATE `famille` SET `libelle_famille_en`="HORSE" WHERE id_famille = 173;
UPDATE `famille` SET `libelle_famille_en`="OTHER MEAT" WHERE id_famille = 174;
UPDATE `famille` SET `libelle_famille_en`="ELABORATED PRODUCTS" WHERE id_famille = 175;
UPDATE `famille` SET `libelle_famille_en`="RAW OFFAL" WHERE id_famille = 176;
UPDATE `famille` SET `libelle_famille_en`="MEAT PETFOOD" WHERE id_famille = 177;
UPDATE `famille` SET `libelle_famille_en`="MARINE FISH" WHERE id_famille = 179;
UPDATE `famille` SET `libelle_famille_en`="FRESHWATER FISH" WHERE id_famille = 180;
UPDATE `famille` SET `libelle_famille_en`="ROASTED SALT FISH" WHERE id_famille = 181;
UPDATE `famille` SET `libelle_famille_en`="SEA SHELL AND MOLLUSC" WHERE id_famille = 182;
UPDATE `famille` SET `libelle_famille_en`="FRESH AND FROZEN CRUSTACI" WHERE id_famille = 183;
UPDATE `famille` SET `libelle_famille_en`="SEAFOOD CATERING PRODUCTS" WHERE id_famille = 184;
UPDATE `famille` SET `libelle_famille_en`="PACKAGED FRESH FISH" WHERE id_famille = 185;
UPDATE `famille` SET `libelle_famille_en`="FROZEN FISH" WHERE id_famille = 186;
UPDATE `famille` SET `libelle_famille_en`="BREAD" WHERE id_famille = 187;
UPDATE `famille` SET `libelle_famille_en`="VIENNESE PASTRY" WHERE id_famille = 188;
UPDATE `famille` SET `libelle_famille_en`="FRESH PASTRY" WHERE id_famille = 189;
UPDATE `famille` SET `libelle_famille_en`="VIENNESE PASTRY" WHERE id_famille = 190;
UPDATE `famille` SET `libelle_famille_en`="DRY PASTRY" WHERE id_famille = 191;
UPDATE `famille` SET `libelle_famille_en`="TWELFTH NIGHT CAKE" WHERE id_famille = 192;
UPDATE `famille` SET `libelle_famille_en`="FRESH CHOCOLATE" WHERE id_famille = 193;
UPDATE `famille` SET `libelle_famille_en`="INDIVIDUAL ICE CREAM" WHERE id_famille = 194;
UPDATE `famille` SET `libelle_famille_en`="BAKERY INGREDIENT" WHERE id_famille = 195;
UPDATE `famille` SET `libelle_famille_en`="PASTRY INGREDIENT" WHERE id_famille = 196;
UPDATE `famille` SET `libelle_famille_en`="BAKERY" WHERE id_famille = 197;
UPDATE `famille` SET `libelle_famille_en`="FRESH FRUITS" WHERE id_famille = 202;
UPDATE `famille` SET `libelle_famille_en`="DRY FRUITS" WHERE id_famille = 203;
UPDATE `famille` SET `libelle_famille_en`="FRESH VEGETABLE" WHERE id_famille = 204;
UPDATE `famille` SET `libelle_famille_en`="DRY VEGETABLE" WHERE id_famille = 205;
UPDATE `famille` SET `libelle_famille_en`="4TH RANGE" WHERE id_famille = 206;
UPDATE `famille` SET `libelle_famille_en`="5TH RANGE" WHERE id_famille = 207;
UPDATE `famille` SET `libelle_famille_en`="CUT FLOWER" WHERE id_famille = 208;
UPDATE `famille` SET `libelle_famille_en`="FIR" WHERE id_famille = 209;
UPDATE `famille` SET `libelle_famille_en`="DRY BREAD PRODUCTS" WHERE id_famille = 210;
UPDATE `famille` SET `libelle_famille_en`="SPECIAL PACKAGED BREAD" WHERE id_famille = 211;
UPDATE `famille` SET `libelle_famille_en`="SWEET BISCUITS" WHERE id_famille = 212;
UPDATE `famille` SET `libelle_famille_en`="INDUSTRIAL PASTRY" WHERE id_famille = 213;
UPDATE `famille` SET `libelle_famille_en`="APERITIF" WHERE id_famille = 214;
UPDATE `famille` SET `libelle_famille_en`="ROASTED COFFEE" WHERE id_famille = 215;
UPDATE `famille` SET `libelle_famille_en`="SOLUBLE COFFEE AND CHICORI" WHERE id_famille = 216;
UPDATE `famille` SET `libelle_famille_en`="CHOCOLATE POWDER DRINK" WHERE id_famille = 217;
UPDATE `famille` SET `libelle_famille_en`="CEREALS" WHERE id_famille = 218;
UPDATE `famille` SET `libelle_famille_en`="TEA AND INFUSION" WHERE id_famille = 219;
UPDATE `famille` SET `libelle_famille_en`="CHOCOLAT BAR" WHERE id_famille = 220;
UPDATE `famille` SET `libelle_famille_en`="SUGAR CONFECTIONNERY" WHERE id_famille = 221;
UPDATE `famille` SET `libelle_famille_en`="CHOCOLATE CONFECTIONNERY" WHERE id_famille = 222;
UPDATE `famille` SET `libelle_famille_en`="DESSERTS" WHERE id_famille = 223;
UPDATE `famille` SET `libelle_famille_en`="PASTRY INGREDIENT" WHERE id_famille = 224;
UPDATE `famille` SET `libelle_famille_en`="CONDENSED MILK AND POWDER MILK" WHERE id_famille = 225;
UPDATE `famille` SET `libelle_famille_en`="SUGAR CONFECTIONNERY" WHERE id_famille = 226;
UPDATE `famille` SET `libelle_famille_en`="PARTY CHOCOLATE" WHERE id_famille = 227;
UPDATE `famille` SET `libelle_famille_en`="DIET PRODUCT" WHERE id_famille = 228;
UPDATE `famille` SET `libelle_famille_en`="FINE FOOD" WHERE id_famille = 229;
UPDATE `famille` SET `libelle_famille_en`="MEAL" WHERE id_famille = 230;
UPDATE `famille` SET `libelle_famille_en`="PUREE SEMOLINA" WHERE id_famille = 231;
UPDATE `famille` SET `libelle_famille_en`="PASTA" WHERE id_famille = 232;
UPDATE `famille` SET `libelle_famille_en`="RICE" WHERE id_famille = 233;
UPDATE `famille` SET `libelle_famille_en`="DRY VEGETABLE" WHERE id_famille = 234;
UPDATE `famille` SET `libelle_famille_en`="BROTHS AND SOUPS" WHERE id_famille = 235;
UPDATE `famille` SET `libelle_famille_en`="CONDIMENTS AND SAUCES" WHERE id_famille = 236;
UPDATE `famille` SET `libelle_famille_en`="SALT PEPPER SPICIES" WHERE id_famille = 237;
UPDATE `famille` SET `libelle_famille_en`="CHIPS" WHERE id_famille = 238;
UPDATE `famille` SET `libelle_famille_en`="OIL FOOD" WHERE id_famille = 239;
UPDATE `famille` SET `libelle_famille_en`="VINAGRE" WHERE id_famille = 240;
UPDATE `famille` SET `libelle_famille_en`="JAMS SPREAD AND HONEY" WHERE id_famille = 241;
UPDATE `famille` SET `libelle_famille_en`="FRUITS WITH SIRUP" WHERE id_famille = 242;
UPDATE `famille` SET `libelle_famille_en`="CANNED VEGETABLE" WHERE id_famille = 243;
UPDATE `famille` SET `libelle_famille_en`="CANNED FISH" WHERE id_famille = 244;
UPDATE `famille` SET `libelle_famille_en`="CANNED MEAT" WHERE id_famille = 245;
UPDATE `famille` SET `libelle_famille_en`="COOKED MEAL" WHERE id_famille = 246;
UPDATE `famille` SET `libelle_famille_en`="KIDS FOOD" WHERE id_famille = 247;
UPDATE `famille` SET `libelle_famille_en`="PETFOOD" WHERE id_famille = 248;
UPDATE `famille` SET `libelle_famille_en`="TRADITIONAL SNACKS" WHERE id_famille = 258;
UPDATE `famille` SET `libelle_famille_en`="MODERN SNACKS" WHERE id_famille = 259;
UPDATE `famille` SET `libelle_famille_en`="SNACKS SELF SERVICE" WHERE id_famille = 260;
UPDATE `famille` SET `libelle_famille_en`="NODDLES" WHERE id_famille = 261;
UPDATE `famille` SET `libelle_famille_en`="SOFT DRINK" WHERE id_famille = 262;
UPDATE `famille` SET `libelle_famille_en`="BEER CIDRE" WHERE id_famille = 263;
UPDATE `famille` SET `libelle_famille_en`="MINERAL WATER" WHERE id_famille = 264;
UPDATE `famille` SET `libelle_famille_en`="COMMON WINE" WHERE id_famille = 265;
UPDATE `famille` SET `libelle_famille_en`="FOREIGN WINE" WHERE id_famille = 266;
UPDATE `famille` SET `libelle_famille_en`="FINE WINE" WHERE id_famille = 267;
UPDATE `famille` SET `libelle_famille_en`="CHAMPAGNE AND SPARKLING WINE" WHERE id_famille = 268;
UPDATE `famille` SET `libelle_famille_en`="APERITIF" WHERE id_famille = 269;
UPDATE `famille` SET `libelle_famille_en`="ALCOHOL AND SPIRIT" WHERE id_famille = 270;
UPDATE `famille` SET `libelle_famille_en`="GRAIN ALCOHOL" WHERE id_famille = 271;
UPDATE `famille` SET `libelle_famille_en`="FLASKS" WHERE id_famille = 272;
UPDATE `famille` SET `libelle_famille_en`="ALCOHOL AND DERIVATIVES" WHERE id_famille = 273;
UPDATE `famille` SET `libelle_famille_en`="WASHING" WHERE id_famille = 274;
UPDATE `famille` SET `libelle_famille_en`="CLEANING PRODUCTS" WHERE id_famille = 275;
UPDATE `famille` SET `libelle_famille_en`="DRUGSTORE" WHERE id_famille = 276;
UPDATE `famille` SET `libelle_famille_en`="HYGIENE PAPER" WHERE id_famille = 277;
UPDATE `famille` SET `libelle_famille_en`="HYGIENE PERFUM" WHERE id_famille = 278;
UPDATE `famille` SET `libelle_famille_en`="BEAUTY PRODUCTS" WHERE id_famille = 279;
UPDATE `famille` SET `libelle_famille_en`="HAIR PRODUCTS" WHERE id_famille = 280;
UPDATE `famille` SET `libelle_famille_en`="PHARMACEUTICAL" WHERE id_famille = 281;
UPDATE `famille` SET `libelle_famille_en`="CUSTOMER BAG" WHERE id_famille = 282;
UPDATE `famille` SET `libelle_famille_en`="BUTCHERY BACKAGE" WHERE id_famille = 283;
UPDATE `famille` SET `libelle_famille_en`="FRUITS AND VEGETABLE PACKAGE" WHERE id_famille = 284;
UPDATE `famille` SET `libelle_famille_en`="FISH PACKAGE" WHERE id_famille = 285;
UPDATE `famille` SET `libelle_famille_en`="BAKERY/PASTRY PACKAGE" WHERE id_famille = 286;
UPDATE `famille` SET `libelle_famille_en`="PASTRY PACKAGE" WHERE id_famille = 287;
UPDATE `famille` SET `libelle_famille_en`="CATERING/CHEESE/DELICATESSEN PACKAGE" WHERE id_famille = 288;
UPDATE `famille` SET `libelle_famille_en`="ISOTHERMAL BAGS" WHERE id_famille = 289;
UPDATE `famille` SET `libelle_famille_en`="GENERAL SERVICE PACKAGE" WHERE id_famille = 290;
UPDATE `famille` SET `libelle_famille_en`="TOOLING HARDWARE" WHERE id_famille = 291;
UPDATE `famille` SET `libelle_famille_en`="ELECTRICITY PRODUCTS" WHERE id_famille = 292;
UPDATE `famille` SET `libelle_famille_en`="DRUGSTORE" WHERE id_famille = 293;
UPDATE `famille` SET `libelle_famille_en`="ELECTRIC TOOLS" WHERE id_famille = 294;
UPDATE `famille` SET `libelle_famille_en`="BATTERY" WHERE id_famille = 295;
UPDATE `famille` SET `libelle_famille_en`="WATCHMAKING" WHERE id_famille = 296;
UPDATE `famille` SET `libelle_famille_en`="GIFT" WHERE id_famille = 297;
UPDATE `famille` SET `libelle_famille_en`="ACCESSORIES FOR PROFESSIONAL BARTENDER" WHERE id_famille = 298;
UPDATE `famille` SET `libelle_famille_en`="MAINTENANCE" WHERE id_famille = 299;
UPDATE `famille` SET `libelle_famille_en`="COFFEE BREAKFAST" WHERE id_famille = 300;
UPDATE `famille` SET `libelle_famille_en`="GLASSWARE" WHERE id_famille = 301;
UPDATE `famille` SET `libelle_famille_en`="DISHWARE" WHERE id_famille = 302;
UPDATE `famille` SET `libelle_famille_en`="TABLE CULTERY" WHERE id_famille = 303;
UPDATE `famille` SET `libelle_famille_en`="TRASH BAGS" WHERE id_famille = 305;
UPDATE `famille` SET `libelle_famille_en`="HOUSEHOLD PRODUCTS" WHERE id_famille = 306;
UPDATE `famille` SET `libelle_famille_en`="DISPOSAL DISHWARE" WHERE id_famille = 307;
UPDATE `famille` SET `libelle_famille_en`="LAUNDRYCARE" WHERE id_famille = 308;
UPDATE `famille` SET `libelle_famille_en`="GAS AND ELECTRICAL COOKING" WHERE id_famille = 309;
UPDATE `famille` SET `libelle_famille_en`="BAKING" WHERE id_famille = 310;
UPDATE `famille` SET `libelle_famille_en`="POCKET LITTERATURE" WHERE id_famille = 311;
UPDATE `famille` SET `libelle_famille_en`="ENVELOP WRITING PAD" WHERE id_famille = 312;
UPDATE `famille` SET `libelle_famille_en`="WRITING" WHERE id_famille = 313;
UPDATE `famille` SET `libelle_famille_en`="STATONERY/NOTEBOOK" WHERE id_famille = 314;
UPDATE `famille` SET `libelle_famille_en`="DOUBLE-SIDED COPIES" WHERE id_famille = 315;
UPDATE `famille` SET `libelle_famille_en`="LOSE-LEAF SHEET" WHERE id_famille = 316;
UPDATE `famille` SET `libelle_famille_en`="OFFICE STATIONERY" WHERE id_famille = 317;
UPDATE `famille` SET `libelle_famille_en`="DRAWING LEISURE CREATIVE" WHERE id_famille = 318;
UPDATE `famille` SET `libelle_famille_en`="SCOLAR EQUIPMENT" WHERE id_famille = 319;
UPDATE `famille` SET `libelle_famille_en`="OFFICE FURNITURE" WHERE id_famille = 320;
UPDATE `famille` SET `libelle_famille_en`="PRESS" WHERE id_famille = 321;
UPDATE `famille` SET `libelle_famille_en`="LITTERATURE" WHERE id_famille = 322;
UPDATE `famille` SET `libelle_famille_en`="LEISURE ACTIVITY" WHERE id_famille = 323;
UPDATE `famille` SET `libelle_famille_en`="YOUTH" WHERE id_famille = 324;
UPDATE `famille` SET `libelle_famille_en`="KID POCKET LITTERATURE" WHERE id_famille = 325;
UPDATE `famille` SET `libelle_famille_en`="DICTIONARY NON-FORMAL EDUCATION" WHERE id_famille = 326;
UPDATE `famille` SET `libelle_famille_en`="DECKS OF CARDS" WHERE id_famille = 327;
UPDATE `famille` SET `libelle_famille_en`="LUGGAGE" WHERE id_famille = 328;
UPDATE `famille` SET `libelle_famille_en`="SCOLAR LEATHER PRODUCTS" WHERE id_famille = 329;
UPDATE `famille` SET `libelle_famille_en`="FRAME POSTERS" WHERE id_famille = 330;
UPDATE `famille` SET `libelle_famille_en`="PROFESSIONAL STATIONERY" WHERE id_famille = 331;
UPDATE `famille` SET `libelle_famille_en`="VIDEO SUPPORT" WHERE id_famille = 332;
UPDATE `famille` SET `libelle_famille_en`="AUDIO SUPPORT" WHERE id_famille = 333;
UPDATE `famille` SET `libelle_famille_en`="DIY CUSTOMER SERVICE" WHERE id_famille = 334;
UPDATE `famille` SET `libelle_famille_en`="OFFICE SPACE" WHERE id_famille = 335;
UPDATE `famille` SET `libelle_famille_en`="GARDENING EQUIPMENT" WHERE id_famille = 336;
UPDATE `famille` SET `libelle_famille_en`="INDOOR PLANT" WHERE id_famille = 337;
UPDATE `famille` SET `libelle_famille_en`="OUTDOOR PLANT" WHERE id_famille = 338;
UPDATE `famille` SET `libelle_famille_en`="BULB SEED PLANT" WHERE id_famille = 339;
UPDATE `famille` SET `libelle_famille_en`="DRY AND ARTIFICIAL FLOWER" WHERE id_famille = 340;
UPDATE `famille` SET `libelle_famille_en`="GARDENING TOOL" WHERE id_famille = 341;
UPDATE `famille` SET `libelle_famille_en`="DECORATION ACCESSORIES" WHERE id_famille = 342;
UPDATE `famille` SET `libelle_famille_en`="MECANICAL AND ELECTRONICAL TOOL" WHERE id_famille = 343;
UPDATE `famille` SET `libelle_famille_en`="WATER SPRAY AND OTHER SPRAYER" WHERE id_famille = 344;
UPDATE `famille` SET `libelle_famille_en`="FENCE" WHERE id_famille = 345;
UPDATE `famille` SET `libelle_famille_en`="SEED AND BULB" WHERE id_famille = 346;
UPDATE `famille` SET `libelle_famille_en`="FERTILISER" WHERE id_famille = 347;
UPDATE `famille` SET `libelle_famille_en`="PETSTORE" WHERE id_famille = 348;
UPDATE `famille` SET `libelle_famille_en`="GARDENING CUSTOMER SERVICE" WHERE id_famille = 349;
UPDATE `famille` SET `libelle_famille_en`="CHRISMAS DECORATION" WHERE id_famille = 350;
UPDATE `famille` SET `libelle_famille_en`="PAINTING" WHERE id_famille = 351;
UPDATE `famille` SET `libelle_famille_en`="WALL AND FLOOR DECORATION" WHERE id_famille = 352;
UPDATE `famille` SET `libelle_famille_en`="LIGHTS" WHERE id_famille = 353;
UPDATE `famille` SET `libelle_famille_en`="KITCHEN AND STORAGE FURNITURE" WHERE id_famille = 354;
UPDATE `famille` SET `libelle_famille_en`="BATHROOM ACCESSORY" WHERE id_famille = 355;
UPDATE `famille` SET `libelle_famille_en`="PROFESSIONAL TOILET" WHERE id_famille = 356;
UPDATE `famille` SET `libelle_famille_en`="LIGHT BULB" WHERE id_famille = 357;
UPDATE `famille` SET `libelle_famille_en`="PLUMBING" WHERE id_famille = 358;
UPDATE `famille` SET `libelle_famille_en`="MASONRY" WHERE id_famille = 359;
UPDATE `famille` SET `libelle_famille_en`="PAINTING WALLPAPER" WHERE id_famille = 360;
UPDATE `famille` SET `libelle_famille_en`="IN-CAR ACCESSORIES" WHERE id_famille = 361;
UPDATE `famille` SET `libelle_famille_en`="OUT-CAR ACCESSORIES" WHERE id_famille = 362;
UPDATE `famille` SET `libelle_famille_en`="TECHNICAL CAR ACCESSORIES" WHERE id_famille = 363;
UPDATE `famille` SET `libelle_famille_en`="LUBRICANT" WHERE id_famille = 364;
UPDATE `famille` SET `libelle_famille_en`="CAR MAINTENANCE" WHERE id_famille = 365;
UPDATE `famille` SET `libelle_famille_en`="KID BIKE" WHERE id_famille = 366;
UPDATE `famille` SET `libelle_famille_en`="WOMAN BIKE" WHERE id_famille = 367;
UPDATE `famille` SET `libelle_famille_en`="MAN BIKE" WHERE id_famille = 368;
UPDATE `famille` SET `libelle_famille_en`="BIKE ACCESSORIES" WHERE id_famille = 369;
UPDATE `famille` SET `libelle_famille_en`="BIKE CUSTOMER SERVICE" WHERE id_famille = 370;
UPDATE `famille` SET `libelle_famille_en`="BABY TOY" WHERE id_famille = 371;
UPDATE `famille` SET `libelle_famille_en`="GIRL TOY" WHERE id_famille = 372;
UPDATE `famille` SET `libelle_famille_en`="BOY TOY" WHERE id_famille = 373;
UPDATE `famille` SET `libelle_famille_en`="MIXT TOY" WHERE id_famille = 374;
UPDATE `famille` SET `libelle_famille_en`="CAMPING" WHERE id_famille = 375;
UPDATE `famille` SET `libelle_famille_en`="OUTDOOR TOY" WHERE id_famille = 376;
UPDATE `famille` SET `libelle_famille_en`="TEAM SPORT" WHERE id_famille = 377;
UPDATE `famille` SET `libelle_famille_en`="OUTDOOR SPORT" WHERE id_famille = 378;
UPDATE `famille` SET `libelle_famille_en`="WINTER SPORT" WHERE id_famille = 379;
UPDATE `famille` SET `libelle_famille_en`="INSIDE SPORT" WHERE id_famille = 380;
UPDATE `famille` SET `libelle_famille_en`="WATER SPORT" WHERE id_famille = 381;
UPDATE `famille` SET `libelle_famille_en`="FISHING" WHERE id_famille = 382;
UPDATE `famille` SET `libelle_famille_en`="CUSTOMER SERVICE LEASURE" WHERE id_famille = 383;
UPDATE `famille` SET `libelle_famille_en`="FESTIVE ARTICLE" WHERE id_famille = 384;
UPDATE `famille` SET `libelle_famille_en`="MOTORCUVLE ACCESSORIES" WHERE id_famille = 385;
UPDATE `famille` SET `libelle_famille_en`="WOOD METAL RATTAN" WHERE id_famille = 386;
UPDATE `famille` SET `libelle_famille_en`="ACCESSORIES FIREPLACE" WHERE id_famille = 387;
UPDATE `famille` SET `libelle_famille_en`="CANDLES AND SCENTS" WHERE id_famille = 388;
UPDATE `famille` SET `libelle_famille_en`="FESTIVE TABLE" WHERE id_famille = 389;
UPDATE `famille` SET `libelle_famille_en`="SELF MAILERS" WHERE id_famille = 390;
UPDATE `famille` SET `libelle_famille_en`="MAKING 0-18 M" WHERE id_famille = 391;
UPDATE `famille` SET `libelle_famille_en`="MAKING HIVER 0-18 M" WHERE id_famille = 392;
UPDATE `famille` SET `libelle_famille_en`="TROUSERS OVERALL 0-18 M" WHERE id_famille = 393;
UPDATE `famille` SET `libelle_famille_en`="TROUSERS OVERALL WINTER 0-19" WHERE id_famille = 394;
UPDATE `famille` SET `libelle_famille_en`="SHIRT 0-18 M" WHERE id_famille = 395;
UPDATE `famille` SET `libelle_famille_en`="SHIRT WINTER 0-18 M" WHERE id_famille = 396;
UPDATE `famille` SET `libelle_famille_en`="SUIT 0-18 M" WHERE id_famille = 397;
UPDATE `famille` SET `libelle_famille_en`="SUIT WINTER 0-18 M" WHERE id_famille = 398;
UPDATE `famille` SET `libelle_famille_en`="OUTFIT 0-18 M" WHERE id_famille = 399;
UPDATE `famille` SET `libelle_famille_en`="OUTFIT WINTER 0-18 M" WHERE id_famille = 400;
UPDATE `famille` SET `libelle_famille_en`="DRESS 0-18 M" WHERE id_famille = 401;
UPDATE `famille` SET `libelle_famille_en`="DRESS WINTER 0-18M" WHERE id_famille = 402;
UPDATE `famille` SET `libelle_famille_en`="KNITTING BABY CLOTHES 0-18 M" WHERE id_famille = 403;
UPDATE `famille` SET `libelle_famille_en`="KNITTING 0-18 M" WHERE id_famille = 404;
UPDATE `famille` SET `libelle_famille_en`="KNITTING WINTER 0-18 M" WHERE id_famille = 405;
UPDATE `famille` SET `libelle_famille_en`="FELT" WHERE id_famille = 406;
UPDATE `famille` SET `libelle_famille_en`="TEE SHIRT POLO 0-18 M" WHERE id_famille = 407;
UPDATE `famille` SET `libelle_famille_en`="SPORT 0-18 M" WHERE id_famille = 408;
UPDATE `famille` SET `libelle_famille_en`="SPORT WINTER 0-18 M" WHERE id_famille = 409;
UPDATE `famille` SET `libelle_famille_en`="NIGHT 0-18 M" WHERE id_famille = 410;
UPDATE `famille` SET `libelle_famille_en`="NUIT WINTER 0-18 M" WHERE id_famille = 411;
UPDATE `famille` SET `libelle_famille_en`="MAKING 2/5 A" WHERE id_famille = 412;
UPDATE `famille` SET `libelle_famille_en`="MAKING WINTER 2/5 A" WHERE id_famille = 413;
UPDATE `famille` SET `libelle_famille_en`="TROUSERS OVERALL 2/5A" WHERE id_famille = 414;
UPDATE `famille` SET `libelle_famille_en`="TROUSERS OVERALL GIRL 2/6" WHERE id_famille = 415;
UPDATE `famille` SET `libelle_famille_en`="TROUSERS OVERALL BOY 2/5A" WHERE id_famille = 416;
UPDATE `famille` SET `libelle_famille_en`="TROUSERS OVERALL WINTER BOY 2/5A" WHERE id_famille = 417;
UPDATE `famille` SET `libelle_famille_en`="SHIRT 2/5 A" WHERE id_famille = 418;
UPDATE `famille` SET `libelle_famille_en`="SHIRT WINTER 2/5 A" WHERE id_famille = 419;
UPDATE `famille` SET `libelle_famille_en`="OUTFIT 2/5 A" WHERE id_famille = 420;
UPDATE `famille` SET `libelle_famille_en`="OUTFIT WINTER 2/5 A" WHERE id_famille = 421;
UPDATE `famille` SET `libelle_famille_en`="DRESS 2/5 A" WHERE id_famille = 422;
UPDATE `famille` SET `libelle_famille_en`="DRESS WINTER 2/5 A" WHERE id_famille = 423;
UPDATE `famille` SET `libelle_famille_en`="SKIRT 2/5 A" WHERE id_famille = 424;
UPDATE `famille` SET `libelle_famille_en`="SKIRT WINTER 2/5 A" WHERE id_famille = 425;
UPDATE `famille` SET `libelle_famille_en`="KNITTING 2/5 A" WHERE id_famille = 426;
UPDATE `famille` SET `libelle_famille_en`="KNITTING WINTER 2/5 A" WHERE id_famille = 427;
UPDATE `famille` SET `libelle_famille_en`="TEE SHIRT POLO 2/5 A" WHERE id_famille = 428;
UPDATE `famille` SET `libelle_famille_en`="TEE SHIRT POLO HIVER 2/5 A" WHERE id_famille = 429;
UPDATE `famille` SET `libelle_famille_en`="SPORT 2/5 A" WHERE id_famille = 430;
UPDATE `famille` SET `libelle_famille_en`="SPORT WINTER 2/5 A" WHERE id_famille = 431;
UPDATE `famille` SET `libelle_famille_en`="NIGHT 2/5 A" WHERE id_famille = 432;
UPDATE `famille` SET `libelle_famille_en`="NUIT WINTER 2/5 A" WHERE id_famille = 433;
UPDATE `famille` SET `libelle_famille_en`="MAKING GIRL 6-16 A" WHERE id_famille = 434;
UPDATE `famille` SET `libelle_famille_en`="MAKING GIRL WINTER 6-16 A" WHERE id_famille = 435;
UPDATE `famille` SET `libelle_famille_en`="MAKING BOY 6-16 A" WHERE id_famille = 436;
UPDATE `famille` SET `libelle_famille_en`="MAKING BOY WINTER 6-16 A" WHERE id_famille = 437;
UPDATE `famille` SET `libelle_famille_en`="OUTFIT GIRL 6-16 A" WHERE id_famille = 438;
UPDATE `famille` SET `libelle_famille_en`="OUTFIT GIRL WINTER 6-16 A" WHERE id_famille = 439;
UPDATE `famille` SET `libelle_famille_en`="TROUSERS GIRL 6-16 A" WHERE id_famille = 440;
UPDATE `famille` SET `libelle_famille_en`="TROUSERS GIRL WINTER 6-16 A" WHERE id_famille = 441;
UPDATE `famille` SET `libelle_famille_en`="TROUSERS BOY 6-16 A" WHERE id_famille = 442;
UPDATE `famille` SET `libelle_famille_en`="TROUSERS BOY WINTER 6-16 A" WHERE id_famille = 443;
UPDATE `famille` SET `libelle_famille_en`="DRESS 6-16 A" WHERE id_famille = 444;
UPDATE `famille` SET `libelle_famille_en`="SKIRT 6-16 A" WHERE id_famille = 445;
UPDATE `famille` SET `libelle_famille_en`="SKIRT WINTER 6-16 A" WHERE id_famille = 446;
UPDATE `famille` SET `libelle_famille_en`="BLOUSE 6-16 A" WHERE id_famille = 447;
UPDATE `famille` SET `libelle_famille_en`="SHIRT BOY 6-16 A" WHERE id_famille = 448;
UPDATE `famille` SET `libelle_famille_en`="UNDERSHIRT GIRL 6-16 A" WHERE id_famille = 449;
UPDATE `famille` SET `libelle_famille_en`="SWEAT GIRL 6-16 A" WHERE id_famille = 450;
UPDATE `famille` SET `libelle_famille_en`="SWEAT GIRL WINTER 6-16 A" WHERE id_famille = 451;
UPDATE `famille` SET `libelle_famille_en`="TEE SHIRT FILLE 6-16 A" WHERE id_famille = 452;
UPDATE `famille` SET `libelle_famille_en`="UNDERSHIRT BOY 6-16 A" WHERE id_famille = 453;
UPDATE `famille` SET `libelle_famille_en`="SWEAT BOY 6-16 A" WHERE id_famille = 454;
UPDATE `famille` SET `libelle_famille_en`="SWEAT BOY WINTER 6-16 A" WHERE id_famille = 455;
UPDATE `famille` SET `libelle_famille_en`="TEE SHIRT POLO BOY 6-16 A" WHERE id_famille = 456;
UPDATE `famille` SET `libelle_famille_en`="MIXED SPORT APAREL" WHERE id_famille = 457;
UPDATE `famille` SET `libelle_famille_en`="SPORT APPAREL MIXED HIVER" WHERE id_famille = 458;
UPDATE `famille` SET `libelle_famille_en`="BATH GIRL 6-16 A" WHERE id_famille = 459;
UPDATE `famille` SET `libelle_famille_en`="BATH BOY 6-16 A" WHERE id_famille = 460;
UPDATE `famille` SET `libelle_famille_en`="NIGHT GIRL 6-16 A" WHERE id_famille = 461;
UPDATE `famille` SET `libelle_famille_en`="NIGHT GIRL WINTER 6-16 A" WHERE id_famille = 462;
UPDATE `famille` SET `libelle_famille_en`="NIGHT BOY 6-16 A" WHERE id_famille = 463;
UPDATE `famille` SET `libelle_famille_en`="NIGHT BOY WINTER 6-16 A" WHERE id_famille = 464;
UPDATE `famille` SET `libelle_famille_en`="WORKING CLOTH 6-16 A" WHERE id_famille = 465;
UPDATE `famille` SET `libelle_famille_en`="MAKING WOMEN" WHERE id_famille = 466;
UPDATE `famille` SET `libelle_famille_en`="MAKING WOMEN WINTER" WHERE id_famille = 467;
UPDATE `famille` SET `libelle_famille_en`="LEATHER WOMEN" WHERE id_famille = 468;
UPDATE `famille` SET `libelle_famille_en`="SHORTS/BERMUDA WOMEN" WHERE id_famille = 469;
UPDATE `famille` SET `libelle_famille_en`="SHORTS/BERMUDA WINTER WOMEN" WHERE id_famille = 470;
UPDATE `famille` SET `libelle_famille_en`="JEANS WOMEN" WHERE id_famille = 471;
UPDATE `famille` SET `libelle_famille_en`="JEANS WOMEN WINTER" WHERE id_famille = 472;
UPDATE `famille` SET `libelle_famille_en`="TROUSERS WOMEN" WHERE id_famille = 473;
UPDATE `famille` SET `libelle_famille_en`="TROUSERS WOMEN WINTER" WHERE id_famille = 474;
UPDATE `famille` SET `libelle_famille_en`="SKIRT WOMEN" WHERE id_famille = 475;
UPDATE `famille` SET `libelle_famille_en`="SKIRT WOMEN" WHERE id_famille = 476;
UPDATE `famille` SET `libelle_famille_en`="DRESS WOMEN" WHERE id_famille = 477;
UPDATE `famille` SET `libelle_famille_en`="DRESS WOMEN WINTER" WHERE id_famille = 478;
UPDATE `famille` SET `libelle_famille_en`="BLOUSE WOMEN" WHERE id_famille = 479;
UPDATE `famille` SET `libelle_famille_en`="BLOUSE WOMEN WINTER" WHERE id_famille = 480;
UPDATE `famille` SET `libelle_famille_en`="KNITTING WOMEN" WHERE id_famille = 481;
UPDATE `famille` SET `libelle_famille_en`="KNITTING WOMEN WINTER" WHERE id_famille = 482;
UPDATE `famille` SET `libelle_famille_en`="TEE SHIRT WOMEN" WHERE id_famille = 483;
UPDATE `famille` SET `libelle_famille_en`="TEE SHIRT WOMEN WINTER" WHERE id_famille = 484;
UPDATE `famille` SET `libelle_famille_en`="SWEATING WOMEN" WHERE id_famille = 485;
UPDATE `famille` SET `libelle_famille_en`="SWEATING WOMEN WINTER" WHERE id_famille = 486;
UPDATE `famille` SET `libelle_famille_en`="SPORT WOMEN" WHERE id_famille = 487;
UPDATE `famille` SET `libelle_famille_en`="SPORT WOMEN WINTER" WHERE id_famille = 488;
UPDATE `famille` SET `libelle_famille_en`="BATH WOMEN" WHERE id_famille = 489;
UPDATE `famille` SET `libelle_famille_en`="LINGERIE WOMEN" WHERE id_famille = 490;
UPDATE `famille` SET `libelle_famille_en`="LINGERIE WOMEN WINTER" WHERE id_famille = 491;
UPDATE `famille` SET `libelle_famille_en`="LARGE SIZED FROM 44" WHERE id_famille = 492;
UPDATE `famille` SET `libelle_famille_en`="LARGE SIZED WINTER FROM 44" WHERE id_famille = 493;
UPDATE `famille` SET `libelle_famille_en`="MAKING MEN" WHERE id_famille = 494;
UPDATE `famille` SET `libelle_famille_en`="MAKING MEN WINTER" WHERE id_famille = 495;
UPDATE `famille` SET `libelle_famille_en`="LEATHER MEN" WHERE id_famille = 496;
UPDATE `famille` SET `libelle_famille_en`="JEANS MEN" WHERE id_famille = 497;
UPDATE `famille` SET `libelle_famille_en`="JEANS MEN" WHERE id_famille = 498;
UPDATE `famille` SET `libelle_famille_en`="TROUSERS MEN" WHERE id_famille = 499;
UPDATE `famille` SET `libelle_famille_en`="TROUSERS MEN WINTER" WHERE id_famille = 500;
UPDATE `famille` SET `libelle_famille_en`="SHIRT MEN" WHERE id_famille = 501;
UPDATE `famille` SET `libelle_famille_en`="SHIRT MEN WINTER" WHERE id_famille = 502;
UPDATE `famille` SET `libelle_famille_en`="KNITTING MEN" WHERE id_famille = 503;
UPDATE `famille` SET `libelle_famille_en`="KNITTING MEN WINTER" WHERE id_famille = 504;
UPDATE `famille` SET `libelle_famille_en`="SWEAT MEN" WHERE id_famille = 505;
UPDATE `famille` SET `libelle_famille_en`="SWEAT MEN WINTER" WHERE id_famille = 506;
UPDATE `famille` SET `libelle_famille_en`="TEE SHIRT POLO MEN" WHERE id_famille = 507;
UPDATE `famille` SET `libelle_famille_en`="TEE SHIRT POLO MEN WINTER" WHERE id_famille = 508;
UPDATE `famille` SET `libelle_famille_en`="SPORT MEN" WHERE id_famille = 509;
UPDATE `famille` SET `libelle_famille_en`="SPORT MEN WINTER" WHERE id_famille = 510;
UPDATE `famille` SET `libelle_famille_en`="BATH MEN" WHERE id_famille = 511;
UPDATE `famille` SET `libelle_famille_en`="NIGHT" WHERE id_famille = 512;
UPDATE `famille` SET `libelle_famille_en`="NIGHT MEN" WHERE id_famille = 513;
UPDATE `famille` SET `libelle_famille_en`="WORK MEN" WHERE id_famille = 514;
UPDATE `famille` SET `libelle_famille_en`="HUNTING AND FISHING" WHERE id_famille = 515;
UPDATE `famille` SET `libelle_famille_en`="MAKING GIRL 2/16 ANS" WHERE id_famille = 516;
UPDATE `famille` SET `libelle_famille_en`="OUTFIT GIRL+BEACH 2/16 ANS" WHERE id_famille = 517;
UPDATE `famille` SET `libelle_famille_en`="TROUSERS GIRL 2/16 ANS" WHERE id_famille = 518;
UPDATE `famille` SET `libelle_famille_en`="DRESS 2/16 ANS" WHERE id_famille = 519;
UPDATE `famille` SET `libelle_famille_en`="SKIRT 2/16 ANS" WHERE id_famille = 520;
UPDATE `famille` SET `libelle_famille_en`="BLOUSE 2/16 ANS" WHERE id_famille = 521;
UPDATE `famille` SET `libelle_famille_en`="KNITTING GIRL 2/16 ANS" WHERE id_famille = 522;
UPDATE `famille` SET `libelle_famille_en`="SWEAT GIRL 2/16 ANS" WHERE id_famille = 523;
UPDATE `famille` SET `libelle_famille_en`="TEE SHIRT GIRL 2/16 ANS" WHERE id_famille = 524;
UPDATE `famille` SET `libelle_famille_en`="BATH 2/16 ANS" WHERE id_famille = 525;
UPDATE `famille` SET `libelle_famille_en`="NIGHT GIRL 2/16 ANS" WHERE id_famille = 526;
UPDATE `famille` SET `libelle_famille_en`="MAKING BOY 2/16 ANS" WHERE id_famille = 527;
UPDATE `famille` SET `libelle_famille_en`="OUTFIT BOY + BEACH 2/16 ANS" WHERE id_famille = 528;
UPDATE `famille` SET `libelle_famille_en`="JEAN\'S 2/16 ANS" WHERE id_famille = 529;
UPDATE `famille` SET `libelle_famille_en`="TROUSERS BOY 2/16 ANS" WHERE id_famille = 530;
UPDATE `famille` SET `libelle_famille_en`="SHIRT 2/16 ANS" WHERE id_famille = 531;
UPDATE `famille` SET `libelle_famille_en`="KNITTING BOY 2/16 ANS" WHERE id_famille = 532;
UPDATE `famille` SET `libelle_famille_en`="SWEAT BOY 2/16 ANS" WHERE id_famille = 533;
UPDATE `famille` SET `libelle_famille_en`="TEE SHIRT BOY 2/16 ANS" WHERE id_famille = 534;
UPDATE `famille` SET `libelle_famille_en`="BATH BOY 2/16 ANS" WHERE id_famille = 535;
UPDATE `famille` SET `libelle_famille_en`="SPORT (MIXTE) 2/16 ANS" WHERE id_famille = 536;
UPDATE `famille` SET `libelle_famille_en`="NIGHT BOY 2/16 ANS" WHERE id_famille = 537;
UPDATE `famille` SET `libelle_famille_en`="WORK CLOTH 2/16 ANS" WHERE id_famille = 538;
UPDATE `famille` SET `libelle_famille_en`="ACCESSORIES 2/16 ANS" WHERE id_famille = 539;
UPDATE `famille` SET `libelle_famille_en`="UNDERWEAR BABY 0 MOIS/5 ANS" WHERE id_famille = 540;
UPDATE `famille` SET `libelle_famille_en`="UNDERWEAR GIRL 6/16 A" WHERE id_famille = 541;
UPDATE `famille` SET `libelle_famille_en`="UNDERWEAR BOY 6/16 A" WHERE id_famille = 542;
UPDATE `famille` SET `libelle_famille_en`="UNDERWEAR WOMEN" WHERE id_famille = 543;
UPDATE `famille` SET `libelle_famille_en`="UNDERWEAR MEN" WHERE id_famille = 544;
UPDATE `famille` SET `libelle_famille_en`="CHAUSSANT M BAS BB 14-15/25-27" WHERE id_famille = 545;
UPDATE `famille` SET `libelle_famille_en`="CHAUSSANT MIXTE 27-30/39-41" WHERE id_famille = 546;
UPDATE `famille` SET `libelle_famille_en`="CHAUSSANT M BAS FE 37-38/39-41" WHERE id_famille = 547;
UPDATE `famille` SET `libelle_famille_en`="CHAUSSANT HOMME 39-40/45-47" WHERE id_famille = 548;
UPDATE `famille` SET `libelle_famille_en`="COLLANT BEBE 3 MOIS/5 ANS" WHERE id_famille = 549;
UPDATE `famille` SET `libelle_famille_en`="COLLANT FILLE 4/16 ANS" WHERE id_famille = 550;
UPDATE `famille` SET `libelle_famille_en`="COLLANT BAS FEMME" WHERE id_famille = 551;
UPDATE `famille` SET `libelle_famille_en`="SWEAT FILLE 2/16 ANS" WHERE id_famille = 552;
UPDATE `famille` SET `libelle_famille_en`="BLANKET" WHERE id_famille = 553;
UPDATE `famille` SET `libelle_famille_en`="BEDCOVER" WHERE id_famille = 554;
UPDATE `famille` SET `libelle_famille_en`="MATTRESSKEEPING" WHERE id_famille = 555;
UPDATE `famille` SET `libelle_famille_en`="DUVET" WHERE id_famille = 556;
UPDATE `famille` SET `libelle_famille_en`="PILLOW BOLSTER CUSHION" WHERE id_famille = 557;
UPDATE `famille` SET `libelle_famille_en`="BED LINEN" WHERE id_famille = 558;
UPDATE `famille` SET `libelle_famille_en`="DUVET COVER" WHERE id_famille = 559;
UPDATE `famille` SET `libelle_famille_en`="BATH LINEN" WHERE id_famille = 560;
UPDATE `famille` SET `libelle_famille_en`="BATHROBE" WHERE id_famille = 561;
UPDATE `famille` SET `libelle_famille_en`="BEACH TOWEL" WHERE id_famille = 562;
UPDATE `famille` SET `libelle_famille_en`="BATHMAT" WHERE id_famille = 563;
UPDATE `famille` SET `libelle_famille_en`="TABLE LINEN" WHERE id_famille = 564;
UPDATE `famille` SET `libelle_famille_en`="KITCHEN LINEN" WHERE id_famille = 565;
UPDATE `famille` SET `libelle_famille_en`="WARPING AND DUAL AIR CURTAIN" WHERE id_famille = 566;
UPDATE `famille` SET `libelle_famille_en`="TISSUE" WHERE id_famille = 567;
UPDATE `famille` SET `libelle_famille_en`="HABERDARSHERIE" WHERE id_famille = 568;
UPDATE `famille` SET `libelle_famille_en`="FURNISHING" WHERE id_famille = 569;
UPDATE `famille` SET `libelle_famille_en`="MEALS" WHERE id_famille = 570;
UPDATE `famille` SET `libelle_famille_en`="HYGIENE-TOILET" WHERE id_famille = 571;
UPDATE `famille` SET `libelle_famille_en`="SECURITY PREVENTION" WHERE id_famille = 572;
UPDATE `famille` SET `libelle_famille_en`="INTERIOR ACCESSORIES" WHERE id_famille = 573;
UPDATE `famille` SET `libelle_famille_en`="OUTPUT ACCESSORIES" WHERE id_famille = 574;
UPDATE `famille` SET `libelle_famille_en`="BED ACCESSORIES" WHERE id_famille = 575;
UPDATE `famille` SET `libelle_famille_en`="GAMES" WHERE id_famille = 576;
UPDATE `famille` SET `libelle_famille_en`="FURNITURE" WHERE id_famille = 577;
UPDATE `famille` SET `libelle_famille_en`="ROLLING EXITS" WHERE id_famille = 578;
UPDATE `famille` SET `libelle_famille_en`="AUTO EXITS" WHERE id_famille = 579;
UPDATE `famille` SET `libelle_famille_en`="HEADGEAR" WHERE id_famille = 580;
UPDATE `famille` SET `libelle_famille_en`="BELT STRAP" WHERE id_famille = 581;
UPDATE `famille` SET `libelle_famille_en`="GLOVES SCARFS" WHERE id_famille = 582;
UPDATE `famille` SET `libelle_famille_en`="COLLAR DRESS HANDKERCHIEF BOW TIE" WHERE id_famille = 583;
UPDATE `famille` SET `libelle_famille_en`="SCARF SHAWL" WHERE id_famille = 584;
UPDATE `famille` SET `libelle_famille_en`="LEATHER STORE" WHERE id_famille = 585;
UPDATE `famille` SET `libelle_famille_en`="PARAPLUIE" WHERE id_famille = 586;
UPDATE `famille` SET `libelle_famille_en`="BABY SHOES" WHERE id_famille = 587;
UPDATE `famille` SET `libelle_famille_en`="BABY SHOES WINTER" WHERE id_famille = 588;
UPDATE `famille` SET `libelle_famille_en`="GIRL SHOES" WHERE id_famille = 589;
UPDATE `famille` SET `libelle_famille_en`="GIRL SHOES WINTER" WHERE id_famille = 590;
UPDATE `famille` SET `libelle_famille_en`="BOY SHOES" WHERE id_famille = 591;
UPDATE `famille` SET `libelle_famille_en`="BOY SHOES WINTER" WHERE id_famille = 592;
UPDATE `famille` SET `libelle_famille_en`="WOMEN SHOES" WHERE id_famille = 593;
UPDATE `famille` SET `libelle_famille_en`="WOMEN SHOES WINTER" WHERE id_famille = 594;
UPDATE `famille` SET `libelle_famille_en`="MEN SHOES" WHERE id_famille = 595;
UPDATE `famille` SET `libelle_famille_en`="SHOES SPORTWEAR" WHERE id_famille = 596;
UPDATE `famille` SET `libelle_famille_en`="BEACH SHOES" WHERE id_famille = 597;
UPDATE `famille` SET `libelle_famille_en`="BABY SPORT" WHERE id_famille = 598;
UPDATE `famille` SET `libelle_famille_en`="CHILD SPORT" WHERE id_famille = 599;
UPDATE `famille` SET `libelle_famille_en`="WOMEN SPORT" WHERE id_famille = 600;
UPDATE `famille` SET `libelle_famille_en`="MEN SPORT" WHERE id_famille = 601;
UPDATE `famille` SET `libelle_famille_en`="SLIPPER BABY" WHERE id_famille = 602;
UPDATE `famille` SET `libelle_famille_en`="SLIPPER BABY WINTER" WHERE id_famille = 603;
UPDATE `famille` SET `libelle_famille_en`="SLIPPER CHILD" WHERE id_famille = 604;
UPDATE `famille` SET `libelle_famille_en`="SLIPPER CHILD WINTER" WHERE id_famille = 605;
UPDATE `famille` SET `libelle_famille_en`="SLIPPER WOMEN" WHERE id_famille = 606;
UPDATE `famille` SET `libelle_famille_en`="SLIPPER WOMEN WINTER" WHERE id_famille = 607;
UPDATE `famille` SET `libelle_famille_en`="SLIPPER MEN" WHERE id_famille = 608;
UPDATE `famille` SET `libelle_famille_en`="SLIPPER MEN WINTER" WHERE id_famille = 609;
UPDATE `famille` SET `libelle_famille_en`="SKI BOOT" WHERE id_famille = 610;
UPDATE `famille` SET `libelle_famille_en`="RAINY BOOT AND WORK" WHERE id_famille = 611;
UPDATE `famille` SET `libelle_famille_en`="SHOES ACCESSORIES" WHERE id_famille = 612;
UPDATE `famille` SET `libelle_famille_en`="BREAKFAST" WHERE id_famille = 613;
UPDATE `famille` SET `libelle_famille_en`="FOOD PREPARATION" WHERE id_famille = 614;
UPDATE `famille` SET `libelle_famille_en`="MICROWAVE" WHERE id_famille = 615;
UPDATE `famille` SET `libelle_famille_en`="LAUNDRY CARE" WHERE id_famille = 616;
UPDATE `famille` SET `libelle_famille_en`="HYGIENE AND BEAUTY" WHERE id_famille = 617;
UPDATE `famille` SET `libelle_famille_en`="RAZOR" WHERE id_famille = 618;
UPDATE `famille` SET `libelle_famille_en`="FLOOR CARE" WHERE id_famille = 619;
UPDATE `famille` SET `libelle_famille_en`="WELL BEING IN THE HOUSE" WHERE id_famille = 620;
UPDATE `famille` SET `libelle_famille_en`="SPARE PARTS" WHERE id_famille = 621;
UPDATE `famille` SET `libelle_famille_en`="WASHING MACHINE, TUMBLE-DRYER" WHERE id_famille = 622;
UPDATE `famille` SET `libelle_famille_en`="WASH DISHES" WHERE id_famille = 623;
UPDATE `famille` SET `libelle_famille_en`="REFRIGERATOR" WHERE id_famille = 624;
UPDATE `famille` SET `libelle_famille_en`="FREEZERS" WHERE id_famille = 625;
UPDATE `famille` SET `libelle_famille_en`="COOKS" WHERE id_famille = 626;
UPDATE `famille` SET `libelle_famille_en`="SLOT-IN" WHERE id_famille = 627;
UPDATE `famille` SET `libelle_famille_en`="PROFESSIONAL MATERIAL" WHERE id_famille = 628;
UPDATE `famille` SET `libelle_famille_en`="MICROWAVE" WHERE id_famille = 629;
UPDATE `famille` SET `libelle_famille_en`="SPARE PARTS  GEM" WHERE id_famille = 630;
UPDATE `famille` SET `libelle_famille_en`="POSTERS" WHERE id_famille = 631;
UPDATE `famille` SET `libelle_famille_en`="FRAMES" WHERE id_famille = 632;
UPDATE `famille` SET `libelle_famille_en`="DEVICES" WHERE id_famille = 633;
UPDATE `famille` SET `libelle_famille_en`="FILM" WHERE id_famille = 634;
UPDATE `famille` SET `libelle_famille_en`="WORKS PHOTO" WHERE id_famille = 635;
UPDATE `famille` SET `libelle_famille_en`="OTHER PRODUCTS" WHERE id_famille = 636;
UPDATE `famille` SET `libelle_famille_en`="ACCESSORIES PHOTO" WHERE id_famille = 637;
UPDATE `famille` SET `libelle_famille_en`="ALBUMS" WHERE id_famille = 638;
UPDATE `famille` SET `libelle_famille_en`="UNDER GLASS" WHERE id_famille = 639;
UPDATE `famille` SET `libelle_famille_en`="HUNTING" WHERE id_famille = 640;
UPDATE `famille` SET `libelle_famille_en`="CRUSH PHOTO" WHERE id_famille = 641;
UPDATE `famille` SET `libelle_famille_en`="GUARANTEED MICROCOMPUTING" WHERE id_famille = 642;
UPDATE `famille` SET `libelle_famille_en`="TELEPHONY" WHERE id_famille = 643;
UPDATE `famille` SET `libelle_famille_en`="DIVERSE CONSUMABLES" WHERE id_famille = 644;
UPDATE `famille` SET `libelle_famille_en`="GAMES CONSOLES" WHERE id_famille = 645;
UPDATE `famille` SET `libelle_famille_en`="MICROCOMPUTING" WHERE id_famille = 646;
UPDATE `famille` SET `libelle_famille_en`="COMPUTING SUPPORTS" WHERE id_famille = 647;
UPDATE `famille` SET `libelle_famille_en`="CALCULATION" WHERE id_famille = 648;
UPDATE `famille` SET `libelle_famille_en`="EQUIPMENT OFFICE" WHERE id_famille = 649;
UPDATE `famille` SET `libelle_famille_en`="SOFTWARE" WHERE id_famille = 650;
UPDATE `famille` SET `libelle_famille_en`="ACCESSORIES MICROPHONE" WHERE id_famille = 651;
UPDATE `famille` SET `libelle_famille_en`="CD-ROM SOFTWARE" WHERE id_famille = 652;
UPDATE `famille` SET `libelle_famille_en`="CLASSIC CD" WHERE id_famille = 653;
UPDATE `famille` SET `libelle_famille_en`="DIVERSE CD" WHERE id_famille = 654;
UPDATE `famille` SET `libelle_famille_en`="CD VARIETY" WHERE id_famille = 655;
UPDATE `famille` SET `libelle_famille_en`="K7" WHERE id_famille = 656;
UPDATE `famille` SET `libelle_famille_en`="MINI DISC" WHERE id_famille = 657;
UPDATE `famille` SET `libelle_famille_en`="SHORT SUPPORTS" WHERE id_famille = 658;
UPDATE `famille` SET `libelle_famille_en`="LASER DISC" WHERE id_famille = 659;
UPDATE `famille` SET `libelle_famille_en`="K7 VIDEO" WHERE id_famille = 660;
UPDATE `famille` SET `libelle_famille_en`="ACCESSOIRIES" WHERE id_famille = 661;
UPDATE `famille` SET `libelle_famille_en`="D.V.D." WHERE id_famille = 662;
UPDATE `famille` SET `libelle_famille_en`="COSTUME JEWELS" WHERE id_famille = 663;
UPDATE `famille` SET `libelle_famille_en`="WATCHMAKER\'S SHOP" WHERE id_famille = 664;
UPDATE `famille` SET `libelle_famille_en`="PRESENTS" WHERE id_famille = 665;
UPDATE `famille` SET `libelle_famille_en`="SUN GLASSES" WHERE id_famille = 666;
UPDATE `famille` SET `libelle_famille_en`="BOX OFFICE" WHERE id_famille = 667;
UPDATE `famille` SET `libelle_famille_en`="JOURNEYS" WHERE id_famille = 668;
UPDATE `famille` SET `libelle_famille_en`="K7 VIDEO" WHERE id_famille = 669;
UPDATE `famille` SET `libelle_famille_en`="DVD" WHERE id_famille = 670;
UPDATE `famille` SET `libelle_famille_en`="LASER DISC" WHERE id_famille = 671;
UPDATE `famille` SET `libelle_famille_en`="TELEVISION SETS" WHERE id_famille = 672;
UPDATE `famille` SET `libelle_famille_en`="ANTENNAS SATELITES" WHERE id_famille = 673;
UPDATE `famille` SET `libelle_famille_en`="VIDEO RECORDER" WHERE id_famille = 674;
UPDATE `famille` SET `libelle_famille_en`="ACCESSORIES TV/VIDEO" WHERE id_famille = 675;
UPDATE `famille` SET `libelle_famille_en`="CAMCORDER" WHERE id_famille = 676;
UPDATE `famille` SET `libelle_famille_en`="READER D.V.D" WHERE id_famille = 677;
UPDATE `famille` SET `libelle_famille_en`="LASER DISC VIDEO" WHERE id_famille = 678;
UPDATE `famille` SET `libelle_famille_en`="SUBSCRIPTIONS / CANAL +" WHERE id_famille = 679;
UPDATE `famille` SET `libelle_famille_en`="INTERNET CONSOLE" WHERE id_famille = 680;
UPDATE `famille` SET `libelle_famille_en`="TPS" WHERE id_famille = 681;
UPDATE `famille` SET `libelle_famille_en`="SMALL SOUND" WHERE id_famille = 682;
UPDATE `famille` SET `libelle_famille_en`="AUTO RADIO" WHERE id_famille = 683;
UPDATE `famille` SET `libelle_famille_en`="WALKMAN" WHERE id_famille = 684;
UPDATE `famille` SET `libelle_famille_en`="RADIO K7" WHERE id_famille = 685;
UPDATE `famille` SET `libelle_famille_en`="HI-FI SYSTEMS" WHERE id_famille = 686;
UPDATE `famille` SET `libelle_famille_en`="LASER DISK PLAYERS" WHERE id_famille = 687;
UPDATE `famille` SET `libelle_famille_en`="SEPARATE ELEMENTS" WHERE id_famille = 688;
UPDATE `famille` SET `libelle_famille_en`="ACCESSORIES SOUND" WHERE id_famille = 689;
UPDATE `famille` SET `libelle_famille_en`="FRAMES OPTICS" WHERE id_famille = 690;
UPDATE `famille` SET `libelle_famille_en`="SOLAR FRAMES" WHERE id_famille = 691;
UPDATE `famille` SET `libelle_famille_en`="GLASSES OPTICS" WHERE id_famille = 692;
UPDATE `famille` SET `libelle_famille_en`="TREATMENT OF  GLASS" WHERE id_famille = 693;
UPDATE `famille` SET `libelle_famille_en`="ACCESSORIES OPTICS" WHERE id_famille = 694;
UPDATE `famille` SET `libelle_famille_en`="PREASSEMBLED GLASSES" WHERE id_famille = 695;
UPDATE `famille` SET `libelle_famille_en`="LENSES OPTICS" WHERE id_famille = 696;
UPDATE `famille` SET `libelle_famille_en`="PRODUCTS LENSES" WHERE id_famille = 697;
UPDATE `famille` SET `libelle_famille_en`="DISPOSABLE LENSES" WHERE id_famille = 698;
UPDATE `famille` SET `libelle_famille_en`="JEWELS FOR THE FINGER" WHERE id_famille = 699;
UPDATE `famille` SET `libelle_famille_en`="JEWELS FOR EARS" WHERE id_famille = 700;
UPDATE `famille` SET `libelle_famille_en`="JEWELS BE SUSPENDED/HAIRPINS" WHERE id_famille = 701;
UPDATE `famille` SET `libelle_famille_en`="JEWELS FOR THE NECK" WHERE id_famille = 702;
UPDATE `famille` SET `libelle_famille_en`="JEWELS FOR THE WRIST" WHERE id_famille = 703;
UPDATE `famille` SET `libelle_famille_en`="SILVER JEWELS" WHERE id_famille = 704;
UPDATE `famille` SET `libelle_famille_en`="PLATED JEWELLERY OR / 9 CARATS" WHERE id_famille = 705;
UPDATE `famille` SET `libelle_famille_en`="COSTUMER SERVICE OR" WHERE id_famille = 706;
UPDATE `famille` SET `libelle_famille_en`="PFLANZENHEILKUNDE" WHERE id_famille = 707;
UPDATE `famille` SET `libelle_famille_en`="DIETETICS" WHERE id_famille = 708;
UPDATE `famille` SET `libelle_famille_en`="BABY" WHERE id_famille = 709;
UPDATE `famille` SET `libelle_famille_en`="PARFUMANTS" WHERE id_famille = 710;
UPDATE `famille` SET `libelle_famille_en`="CARE HYGIENE" WHERE id_famille = 711;
UPDATE `famille` SET `libelle_famille_en`="AUTOMEDICATION" WHERE id_famille = 712;
UPDATE `famille` SET `libelle_famille_en`="VETERINARY PRODUCTS" WHERE id_famille = 713;
UPDATE `famille` SET `libelle_famille_en`="ACCESSORIES NON-PHARMACEUTICAL CHEMIST\'S" WHERE id_famille = 714;
UPDATE `famille` SET `libelle_famille_en`="SOLAR ENERGY" WHERE id_famille = 715;
UPDATE `famille` SET `libelle_famille_en`="ORAL HYGIENE" WHERE id_famille = 716;
UPDATE `famille` SET `libelle_famille_en`="HYGIENE MEN PERFUME SHOP" WHERE id_famille = 717;
UPDATE `famille` SET `libelle_famille_en`="CAPILLARY" WHERE id_famille = 718;
UPDATE `famille` SET `libelle_famille_en`="DERMATOLOGICAL CARE" WHERE id_famille = 719;
UPDATE `famille` SET `libelle_famille_en`="MAKE-UP" WHERE id_famille = 720;
UPDATE `famille` SET `libelle_famille_en`="BODYCARE" WHERE id_famille = 721;
UPDATE `famille` SET `libelle_famille_en`="PHARMACY" WHERE id_famille = 722;
UPDATE `famille` SET `libelle_famille_en`="LUXURY PERFUME SHOP" WHERE id_famille = 723;
UPDATE `famille` SET `libelle_famille_en`="RETURN THE DEPOSIT" WHERE id_famille = 724;
UPDATE `famille` SET `libelle_famille_en`="OFFICE AUTOMATION" WHERE id_famille = 725;
UPDATE `famille` SET `libelle_famille_en`="HUNTING AND ALARM" WHERE id_famille = 726;
UPDATE `famille` SET `libelle_famille_en`="TECHNICAL MOTORCYCLE" WHERE id_famille = 727;
UPDATE `famille` SET `libelle_famille_en`="EQUIPMENT MOTORCYCLE" WHERE id_famille = 728;
UPDATE `famille` SET `libelle_famille_en`="PILOT EQUIPMENT" WHERE id_famille = 729;
UPDATE `famille` SET `libelle_famille_en`="MICROCOMPUTERS" WHERE id_famille = 730;
UPDATE `famille` SET `libelle_famille_en`="PERIPHERALS" WHERE id_famille = 731;
UPDATE `famille` SET `libelle_famille_en`="MICROCOMPUTING" WHERE id_famille = 732;
UPDATE `famille` SET `libelle_famille_en`="CONSUMABLES MICROPHONE" WHERE id_famille = 733;
UPDATE `famille` SET `libelle_famille_en`="FURNITURE MICROPHONE" WHERE id_famille = 734;
UPDATE `famille` SET `libelle_famille_en`="MAGNETIC TAPES" WHERE id_famille = 735;
UPDATE `famille` SET `libelle_famille_en`="INTERNET" WHERE id_famille = 736;
UPDATE `famille` SET `libelle_famille_en`="CIGARETTES + TOBACCO" WHERE id_famille = 737;
UPDATE `famille` SET `libelle_famille_en`="GASOLINE" WHERE id_famille = 738;
UPDATE `famille` SET `libelle_famille_en`="HEATING OIL" WHERE id_famille = 739;
UPDATE `famille` SET `libelle_famille_en`="GASOLINE STANDS OUT NATIONAL" WHERE id_famille = 740;
UPDATE `famille` SET `libelle_famille_en`="GAS BOTTLE 13 ET 35 KG" WHERE id_famille = 741;
UPDATE `famille` SET `libelle_famille_en`="COAL" WHERE id_famille = 742;
UPDATE `famille` SET `libelle_famille_en`="FIREWOOD" WHERE id_famille = 743;
UPDATE `famille` SET `libelle_famille_en`="FUEL OIL NATIONAL BRAND" WHERE id_famille = 744;
UPDATE `famille` SET `libelle_famille_en`="SUPER UNLEADED GASOLINE 95" WHERE id_famille = 745;
UPDATE `famille` SET `libelle_famille_en`="SUPER UNLEADED GASOLINE 98" WHERE id_famille = 746;
UPDATE `famille` SET `libelle_famille_en`="SUPER LEADED" WHERE id_famille = 747;
UPDATE `famille` SET `libelle_famille_en`="GASOIL" WHERE id_famille = 748;
UPDATE `famille` SET `libelle_famille_en`="LPG" WHERE id_famille = 749;
UPDATE `famille` SET `libelle_famille_en`="STEAM-PRESSING" WHERE id_famille = 750;
UPDATE `famille` SET `libelle_famille_en`="CABIN PHOTO" WHERE id_famille = 751;
UPDATE `famille` SET `libelle_famille_en`="SETPOINT" WHERE id_famille = 752;
UPDATE `famille` SET `libelle_famille_en`="RECIPES PHOTOCOPIES" WHERE id_famille = 753;
UPDATE `famille` SET `libelle_famille_en`="RENT SPACES OUT" WHERE id_famille = 754;
UPDATE `famille` SET `libelle_famille_en`="RENT PARKING LOT" WHERE id_famille = 755;
UPDATE `famille` SET `libelle_famille_en`="STAMP CEDIFETE" WHERE id_famille = 756;
UPDATE `famille` SET `libelle_famille_en`="CAMERA AND CAMCORDER" WHERE id_famille = 757;
UPDATE `famille` SET `libelle_famille_en`="PACKAGINGS" WHERE id_famille = 758;
UPDATE `famille` SET `libelle_famille_en`="SERVICES" WHERE id_famille = 759;
UPDATE `famille` SET `libelle_famille_en`="DECONSIGNE" WHERE id_famille = 760;
UPDATE `famille` SET `libelle_famille_en`="MISCELLANEOUS" WHERE id_famille = 761;
UPDATE `famille` SET `libelle_famille_en`="BOUYGUES TELECOM" WHERE id_famille = 762;
UPDATE `famille` SET `libelle_famille_en`="BONUS G.S.M" WHERE id_famille = 763;
UPDATE `famille` SET `libelle_famille_en`="CASKET" WHERE id_famille = 764;
UPDATE `famille` SET `libelle_famille_en`="MOBILE ACCESSORIES" WHERE id_famille = 765;
UPDATE `famille` SET `libelle_famille_en`="WIRED SUBSCRIPTIONS" WHERE id_famille = 766;
UPDATE `famille` SET `libelle_famille_en`="CUSTOMER SERVICE WHITE" WHERE id_famille = 767;
UPDATE `famille` SET `libelle_famille_en`="CUSTOMER SERVICE PEM" WHERE id_famille = 768;
UPDATE `famille` SET `libelle_famille_en`="CUSTOMER SERVICE BROWN" WHERE id_famille = 769;
UPDATE `famille` SET `libelle_famille_en`="EXTENSION OF GUARANTEE" WHERE id_famille = 770;
UPDATE `famille` SET `libelle_famille_en`="SUBSCRIPTION CANAL+" WHERE id_famille = 771;
UPDATE `famille` SET `libelle_famille_en`="DELIVERY" WHERE id_famille = 772;
UPDATE `famille` SET `libelle_famille_en`="STATION WASH AUTOMOBILE" WHERE id_famille = 773;
UPDATE `famille` SET `libelle_famille_en`="MISCELLANEOUS" WHERE id_famille = 774;
UPDATE `famille` SET `libelle_famille_en`="MISCELLANEOUS" WHERE id_famille = 775;
'
        );
    }

    public function down(Schema $schema)
    {

    }
}
